<html>
<head>
	<title> РЭУ Кемеровский институт </title>
	<meta http-equiv = "Content - Type" content = "text/html; cherset = windows - 1251">
	<META name = "Author" content = "http://ailus.ru"><meta name = "Copyright" content = "http://ailus.tu">
</head>

<body leftmargin = "0" topmargin = "0" marginwidth = "0" marginheight = "0" rigthmargin = "0" bo9ttommargin = "0" bgcolor = "#ffffff">
<kink href = "index.css" type = "text/css" rel = "STYLESHEET">

<table border = 1 width = 100% height = 20%>

<td width = 100% height = 20% align = center> Лабораторные работы по курсу "Динамические вэб-системы в экономике" <br> Студента группы ПИ-163: Шемонаевой Дарьи <br> Проверил к.т.н. доц. Назимов А.С.
<td>

</table>

<table border = 1 width = 100% height = 70%>
<td width = 30% heigth = 70% align = left>>
<a href = "orderform.php"> Первая лабораторная работа </a>
<br><br>
<a href = "orderform_2.php"> Вторая лабораторная работа </a>
<br><br>
<a href = ""> Третья лабораторная работа </a>
<br><br>
<a href = ""> Четвёртая лабораторная работа </a>
<br><br>
<a href = ""> Пятая лабораторная работа </a>
<br><br>

</td>
<td width = 70% height = 70% align = center>